In [1]:
import numpy as np

In [4]:
### np is alias for numpy
### create arrays using numpy

arr1=np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))

print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
### 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ###1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
### 2D array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [12]:
import numpy as np

In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition

print("Addition: ", arr1+arr2)

print("Subtraction: ", arr1-arr2)

print("multiplication: ", arr1*arr2)

print("division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]
division:  [0.1 0.1 0.1 0.1 0.1]


In [22]:
### Universal function

arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
### Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0][1]

np.int64(2)

In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [31]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [33]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [34]:
### Modify Array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
###statistical concept
###to have a mean of zero and standard deviation is 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [38]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)
print(mean)

median = np.median(data)
print(median)

variance = np.var(data)
print(variance)

std_dev = np.std(data)
print(std_dev)

5.5
5.5
8.25
2.8722813232690143


In [44]:
### Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data < 8)]

array([6, 7])